#include "block_registry.h"

Material block_registry_get_material(Block block, Face face, TextureAtlas *textures) {
  if(face == FACE_RIGHT) return REGISTERED_BLOCKS[block].right;
  else if(face == FACE_LEFT) return REGISTERED_BLOCKS[block].left;
  else if(face == FACE_TOP) return REGISTERED_BLOCKS[block].top;
  else if(face == FACE_BOTTOM) return REGISTERED_BLOCKS[block].bottom;
  else if(face == FACE_FRONT) return REGISTERED_BLOCKS[block].front;
  else return REGISTERED_BLOCKS[block].back;
}

const BlockDefinition REGISTERED_BLOCKS[BLOCK_COUNT] = {
  [BLOCK_AIR] = (BlockDefinition){
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {0, 0}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {0, 0}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {0, 0}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {0, 0}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {0, 0}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {0, 0}, .animated = false},
    true,
    false,
  },
  [BLOCK_GRASS] = (BlockDefinition){
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {38, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 11}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {22, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {22, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {22, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {22, 36}, .animated = false},
    false,
    true,
  },
  [BLOCK_STONE] = (BlockDefinition){
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {40, 40}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {40, 40}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {40, 40}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {40, 40}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {40, 40}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {40, 40}, .animated = false},
    false,
    true,
  },
  [BLOCK_DIRT] = (BlockDefinition){ 
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 11}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 11}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 11}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 11}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 11}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 11}, .animated = false},
    false,
    true,
  },
  [BLOCK_TNT] = (BlockDefinition){ 
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {14, 41}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {12, 41}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {13, 41}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {13, 41}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {13, 41}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {13, 41}, .animated = false},
    false,
    true,
  },
  [BLOCK_DIAMOND_ORE] = (BlockDefinition){ 
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 9}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 9}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 9}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 9}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 9}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 9}, .animated = false},
    false,
    true,
  },
  [BLOCK_GOLD_ORE] = (BlockDefinition){ 
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {19, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {19, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {19, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {19, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {19, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {19, 36}, .animated = false},
    false,
    true,
  },
  [BLOCK_IRON_ORE] = (BlockDefinition){ 
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {0, 37}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {0, 37}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {0, 37}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {0, 37}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {0, 37}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {0, 37}, .animated = false},
    false,
    true,
  },
  [BLOCK_COAL_ORE] = (BlockDefinition){ 
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 4}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 4}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 4}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 4}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 4}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 4}, .animated = false},
    false,
    true,
  },
   [BLOCK_OAK_LOG] = (BlockDefinition){ 
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {29, 38}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {29, 38}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {28, 38}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {28, 38}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {28, 38}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {28, 38}, .animated = false},
    false,
    true,
  },
   [BLOCK_OAK_LEAVES] = (BlockDefinition){ 
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {52, 47}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {52, 47}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {52, 47}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {52, 47}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {52, 47}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {52, 47}, .animated = false},
    false,
    true,
  },
  [BLOCK_OAK_PLANKS] = (BlockDefinition){
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {30, 38}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {30, 38}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {30, 38}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {30, 38}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {30, 38}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {30, 38}, .animated = false},
    false,
    true,
  },
  [BLOCK_DIAMOND] = (BlockDefinition){
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 8}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 8}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 8}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 8}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 8}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {64, 8}, .animated = false},
    false,
    true,
  },
  [BLOCK_GOLD] = (BlockDefinition){
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {18, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {18, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {18, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {18, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {18, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {18, 36}, .animated = false},
    false,
    true,
  },
  [BLOCK_IRON] = (BlockDefinition){
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 36}, .animated = false},
    false,
    true,
  },
  [BLOCK_COAL] = (BlockDefinition){
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 3}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 3}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 3}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 3}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 3}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 3}, .animated = false},
    false,
    true,
  },
  [BLOCK_FURNACE] = (BlockDefinition){
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {14, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {14, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {14, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {14, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {11, 36}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {13, 36}, .animated = false},
    false,
    true,
  },
  [BLOCK_CRAFTING_TABLE] = (BlockDefinition){
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 27}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {30, 38}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 25}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 26}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 26}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 25}, .animated = false},
    false,
    true,
  },
  [BLOCK_BEDROCK] = (BlockDefinition){
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {58, 25}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {58, 25}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {58, 25}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {58, 25}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {58, 25}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {58, 25}, .animated = false},
    false,
    true,
  },
  [BLOCK_COBBLESTONE] = (BlockDefinition){
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 6}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 6}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 6}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 6}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 6}, .animated = false},
    (Material) {.color = (Color) {1.f, 1.f, 1.f, 1.f}, .tile = (AtlasTile) {62, 6}, .animated = false},
    false,
    true,
  },
  [BLOCK_WATER] = (BlockDefinition){
    (Material) {.color = (Color) {35.f / 255.f, 70.f / 255.f, 204.f / 255.f, 1.f}, .tile = (AtlasTile) {56, 20}, .animated = true},
    (Material) {.color = (Color) {35.f / 255.f, 70.f / 255.f, 204.f / 255.f, 1.f}, .tile = (AtlasTile) {56, 20}, .animated = true},
    (Material) {.color = (Color) {35.f / 255.f, 70.f / 255.f, 204.f / 255.f, 1.f}, .tile = (AtlasTile) {56, 20}, .animated = true},
    (Material) {.color = (Color) {35.f / 255.f, 70.f / 255.f, 204.f / 255.f, 1.f}, .tile = (AtlasTile) {56, 20}, .animated = true},
    (Material) {.color = (Color) {35.f / 255.f, 70.f / 255.f, 204.f / 255.f, 1.f}, .tile = (AtlasTile) {56, 20}, .animated = true},
    (Material) {.color = (Color) {35.f / 255.f, 70.f / 255.f, 204.f / 255.f, 1.f}, .tile = (AtlasTile) {56, 20}, .animated = true},
    false,
    true,
  },
};