#include "block_registry.h"

const BlockDefinition REGISTERED_BLOCKS[BLOCK_COUNT] = {
  [BLOCK_AIR] = (BlockDefinition){
    (AtlasTile) {0, 0},
    (AtlasTile) {0, 0},
    (AtlasTile) {0, 0},
    (AtlasTile) {0, 0},
    (AtlasTile) {0, 0},
    (AtlasTile) {0, 0},
    true,
    false,
  },
  [BLOCK_GRASS] = (BlockDefinition){
    (AtlasTile) {38, 36},
    (AtlasTile) {64, 11},
    (AtlasTile) {22, 36},
    (AtlasTile) {22, 36},
    (AtlasTile) {22, 36},
    (AtlasTile) {22, 36},
    false,
    true,
  },
  [BLOCK_STONE] = (BlockDefinition){
    (AtlasTile) {40, 40},
    (AtlasTile) {40, 40},
    (AtlasTile) {40, 40},
    (AtlasTile) {40, 40},
    (AtlasTile) {40, 40},
    (AtlasTile) {40, 40},
    false,
    true,
  },
  [BLOCK_DIRT] = (BlockDefinition){ 
    (AtlasTile) {64, 11},
    (AtlasTile) {64, 11},
    (AtlasTile) {64, 11},
    (AtlasTile) {64, 11},
    (AtlasTile) {64, 11},
    (AtlasTile) {64, 11},
    false,
    true,
  },
  [BLOCK_TNT] = (BlockDefinition){ 
    (AtlasTile) {14, 41},
    (AtlasTile) {12, 41},
    (AtlasTile) {13, 41},
    (AtlasTile) {13, 41},
    (AtlasTile) {13, 41},
    (AtlasTile) {13, 41},
    false,
    true,
  },
  [BLOCK_DIAMOND_ORE] = (BlockDefinition){ 
    (AtlasTile) {64, 9},
    (AtlasTile) {64, 9},
    (AtlasTile) {64, 9},
    (AtlasTile) {64, 9},
    (AtlasTile) {64, 9},
    (AtlasTile) {64, 9},
    false,
    true,
  },
  [BLOCK_GOLD_ORE] = (BlockDefinition){ 
    (AtlasTile) {19, 36},
    (AtlasTile) {19, 36},
    (AtlasTile) {19, 36},
    (AtlasTile) {19, 36},
    (AtlasTile) {19, 36},
    (AtlasTile) {19, 36},
    false,
    true,
  },
  [BLOCK_IRON_ORE] = (BlockDefinition){ 
    (AtlasTile) {0, 37},
    (AtlasTile) {0, 37},
    (AtlasTile) {0, 37},
    (AtlasTile) {0, 37},
    (AtlasTile) {0, 37},
    (AtlasTile) {0, 37},
    false,
    true,
  },
  [BLOCK_COAL_ORE] = (BlockDefinition){ 
    (AtlasTile) {62, 4},
    (AtlasTile) {62, 4},
    (AtlasTile) {62, 4},
    (AtlasTile) {62, 4},
    (AtlasTile) {62, 4},
    (AtlasTile) {62, 4},
    false,
    true,
  },
   [BLOCK_OAK_LOG] = (BlockDefinition){ 
    (AtlasTile) {29, 38},
    (AtlasTile) {29, 38},
    (AtlasTile) {28, 38},
    (AtlasTile) {28, 38},
    (AtlasTile) {28, 38},
    (AtlasTile) {28, 38},
    false,
    true,
  },
   [BLOCK_OAK_LEAVES] = (BlockDefinition){ 
    (AtlasTile) {52, 47},
    (AtlasTile) {52, 47},
    (AtlasTile) {52, 47},
    (AtlasTile) {52, 47},
    (AtlasTile) {52, 47},
    (AtlasTile) {52, 47},
    false,
    true,
  },
  [BLOCK_OAK_PLANKS] = (BlockDefinition){
    (AtlasTile) {30, 38},
    (AtlasTile) {30, 38},
    (AtlasTile) {30, 38},
    (AtlasTile) {30, 38},
    (AtlasTile) {30, 38},
    (AtlasTile) {30, 38},
    false,
    true,
  },
  [BLOCK_DIAMOND] = (BlockDefinition){
    (AtlasTile) {64, 8},
    (AtlasTile) {64, 8},
    (AtlasTile) {64, 8},
    (AtlasTile) {64, 8},
    (AtlasTile) {64, 8},
    (AtlasTile) {64, 8},
    false,
    true,
  },
  [BLOCK_GOLD] = (BlockDefinition){
    (AtlasTile) {18, 36},
    (AtlasTile) {18, 36},
    (AtlasTile) {18, 36},
    (AtlasTile) {18, 36},
    (AtlasTile) {18, 36},
    (AtlasTile) {18, 36},
    false,
    true,
  },
  [BLOCK_IRON] = (BlockDefinition){
    (AtlasTile) {62, 36},
    (AtlasTile) {62, 36},
    (AtlasTile) {62, 36},
    (AtlasTile) {62, 36},
    (AtlasTile) {62, 36},
    (AtlasTile) {62, 36},
    false,
    true,
  },
  [BLOCK_COAL] = (BlockDefinition){
    (AtlasTile) {62, 3},
    (AtlasTile) {62, 3},
    (AtlasTile) {62, 3},
    (AtlasTile) {62, 3},
    (AtlasTile) {62, 3},
    (AtlasTile) {62, 3},
    false,
    true,
  },
  [BLOCK_FURNACE] = (BlockDefinition){
    (AtlasTile) {14, 36},
    (AtlasTile) {14, 36},
    (AtlasTile) {14, 36},
    (AtlasTile) {14, 36},
    (AtlasTile) {11, 36},
    (AtlasTile) {13, 36},
    false,
    true,
  },
  [BLOCK_CRAFTING_TABLE] = (BlockDefinition){
    (AtlasTile) {62, 27},
    (AtlasTile) {30, 38},
    (AtlasTile) {62, 25},
    (AtlasTile) {62, 26},
    (AtlasTile) {62, 26},
    (AtlasTile) {62, 25},
    false,
    true,
  },
  [BLOCK_BEDROCK] = (BlockDefinition){
    (AtlasTile) {58, 25},
    (AtlasTile) {58, 25},
    (AtlasTile) {58, 25},
    (AtlasTile) {58, 25},
    (AtlasTile) {58, 25},
    (AtlasTile) {58, 25},
    false,
    true,
  },
  [BLOCK_COBBLESTONE] = (BlockDefinition){
    (AtlasTile) {62, 6},
    (AtlasTile) {62, 6},
    (AtlasTile) {62, 6},
    (AtlasTile) {62, 6},
    (AtlasTile) {62, 6},
    (AtlasTile) {62, 6},
    false,
    true,
  },
};