#pragma once

typedef enum {
  BLOCK_AIR, BLOCK_GRASS, BLOCK_STONE, BLOCK_DIRT,
  BLOCK_TNT, BLOCK_DIAMOND_ORE, BLOCK_GOLD_ORE,
  BLOCK_IRON_ORE, BLOCK_COAL_ORE, BLOCK_OAK_LOG, 
  BLOCK_OAK_LEAVES, BLOCK_OAK_PLANKS, BLOCK_DIAMOND,
  BLOCK_GOLD, BLOCK_IRON, BLOCK_COAL, BLOCK_FURNACE,
  BLOCK_CRAFTING_TABLE, BLOCK_BEDROCK, BLOCK_COBBLESTONE,
  BLOCK_COUNT 
} Block;